name: Check POC
on: [push, pull_request]
jobs:
  check_poc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare
        run: |
          cd $GITHUB_WORKSPACE && \
          wget -nv https://github.com/chaitin/gamma/releases/download/v0.0.2/gamma_linux_amd64 && \
          pip3 install yamllint && \
          chmod +x gamma_linux_amd64
      - name: Check POC
        run: |
          cd $GITHUB_WORKSPACE && \
          ./gamma_linux_amd64 lint --script "./scripts/poc/*" --rules filename,filepath,yamlschema,yamllint,cellint && \
          ./gamma_linux_amd64 lint --script "./scripts/fingerprint/*" --type fingerprint  --rules filename,filepath,yamlschema,yamllint,cellint
